apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: amt-configure
  labels:
    k8s-app: amt-configure
spec:
  selector:
    matchLabels:
      name: amt-configure
  template:
    metadata:
      labels:
        name: amt-configure
    spec:
      hostNetwork: true
      nodeSelector:
        feature.node.kubernetes.io/intel-amt: "true"
      containers:
          - name: meshcmd
            image: boxcutter/meshcmd:1.1.3
            imagePullPolicy: IfNotPresent
            command: ['/bin/bash', '-c', 'while /bin/true; do sleep $((1 + $RANDOM % {{ .Values.config.refreshSplay }})); meshcmd amtconfig --url "${URL}" --id "${ID}" --serverhttpshash "${SERVERHASH}"; sleep {{ .Values.config.refreshInterval }}; done']
            securityContext:
              privileged: true
            envFrom:
              - secretRef:
                  name: amt-settings
            volumeMounts:
              - mountPath: /dev/mei0
                name: dev-mei0
      volumes:
        - name: dev-mei0
          hostPath:
            path: /dev/mei0
