apiVersion: v1
kind: Service
metadata:
  name: {{ include "mealie.fullname" . }}-frontend
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mealie.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
