apiVersion: v1
kind: Service
metadata:
  name: {{ include "mealie.fullname" . }}-api
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mealie.selectorLabels" . | nindent 4 }}
    mealie.danielhall.me/is-api: "true"
