# Default values for amt-configure.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  url: ""
  id: ""
  serverhash: ""
  refreshInterval: 3240
  refreshSplay: 720

image:
  repository: boxcutter/meshcmd
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.1.3"

imagePullSecrets: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}
