apiVersion: v1
kind: Service
metadata:
  name: {{ template "frigate.fullname" . }}
  labels:
{{ include "frigate.labels" . | indent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if (or (eq .Values.service.type "ClusterIP") (empty .Values.service.type)) }}
  type: ClusterIP
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{end}}
{{- else if eq .Values.service.type "LoadBalancer" }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.service.type }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
  {{- if .Values.service.http.enabled }}
    - name: http
      port: {{ .Values.service.http.port }}
      protocol: TCP
      targetPort: http
  {{- end }}
  {{- if .Values.service.rtmp.enabled }}
    - name: rtmp
      port: {{ .Values.service.rtmp.port }}
      protocol: TCP
      targetPort: rtmp
  {{- end }}
  {{- if .Values.service.rtsp.enabled }}
    - name: rtsp
      port: {{ .Values.service.rtsp.port }}
      protocol: TCP
      targetPort: rtsp
  {{- end }}
  {{- if .Values.service.webrtc.enabled }}
    - name: webrtc-tcp
      port: {{ .Values.service.webrtc.port }}
      protocol: TCP
      targetPort: webrtc-tcp
    - name: webrtc-udp
      port: {{ .Values.service.webrtc.port }}
      protocol: UDP
      targetPort: webrtc-udp
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "frigate.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
