name: Lint and Test Charts

on:
  pull_request:

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup chart-testing
        uses: helm/chart-testing-action@v2.3.1
 
      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Run helm-docs
        run: .github/helm-docs.sh

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

  kubeconform-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
    strategy:
      matrix:
        k8s:
          - 1.26.2
          - 1.25.6
          - 1.24.10
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Validate Helm Chart
        uses: docker://ghcr.io/wdaan/helm-kubeconform-action:v0.1.7
        env:
          ADDITIONAL_SCHEMA_PATHS: |
            schemas/{{ .ResourceKind }}.json
          CHARTS_DIRECTORY: "charts"
          KUBECONFORM_STRICT: "true"
          HELM_UPDATE_DEPENDENCIES: "true"
          IGNORE_MISSING_SCHEMAS: "false"
          KUBERNETES_VERSION: "${{ matrix.k8s }}"


  kind-test:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
    if: needs.lint-chart.outputs.changed == 'true'
    strategy:
      matrix:
        k8s:
        # Get versions from: https://hub.docker.com/r/kindest/node/tags
          - v1.26.0
          - v1.25.3
          - v1.24.7
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}

      - name: Run chart-testing (install)
        run: ct install

  summary-test:
    runs-on: ubuntu-latest
    needs:
      - kubeconform-chart
      - kind-test
    if: always()
    steps:
      - name: All tests ok
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Some tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
